openapi: 3.0.0
info:
  title: Anthropic API
  version: 2023-06-01
  description: API for interacting with Anthropic's AI models
paths:
  /v1/messages:
    post:
      summary: Create a Message
      description: Send a structured list of input messages with text and/or image content, and the model will generate the next message in the conversation.
      requestBody:
        required: true
        content:
          application/json:    
            schema:
              type: object
              required:
                - model
                - messages
                - max_tokens
              properties:
                model:
                  type: string
                  description: The model that will complete your prompt.
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum: [user, assistant]
                      content:
                        oneOf:
                          - type: string
                          - type: array
                            items:
                              type: object
                              required:
                                - type
                              properties:
                                type:
                                  type: string
                                  enum: [text, image]
                                text:
                                  type: string
                                source:
                                  type: object
                                  required:
                                    - type
                                    - media_type
                                    - data
                                  properties:
                                    type: 
                                      type: string
                                      enum: [base64]
                                    media_type:
                                      type: string
                                      enum: [image/jpeg, image/png, image/gif, image/webp] 
                                    data:
                                      type: string
                                      format: byte
                max_tokens:
                  type: integer
                  description: The maximum number of tokens to generate before stopping.
                metadata:
                  type: object
                  description: An object describing metadata about the request.
                stop_sequences:
                  type: array
                  items:
                    type: string
                  description: Custom text sequences that will cause the model to stop generating.
                stream:
                  type: boolean
                  description: Whether to incrementally stream the response using server-sent events.
                system:
                  type: string
                  description: A system prompt providing context and instructions to the model.
                temperature:
                  type: number
                  description: Amount of randomness injected into the response. Between 0.0 and 1.0.
                tools:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      input_schema:
                        type: object
                  description: Definitions of tools the model may use.
                top_k:
                  type: integer
                  description: Only sample from the top K options for each subsequent token.
                top_p:
                  type: number 
                  description: Use nucleus sampling, altering cumulative probability cutoff.
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  id:
                    type: string
                  content:
                    type: array
                    items:
                      oneOf:
                        - type: object
                          properties:
                            text: 
                              type: string
                        - type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            input:
                              type: object
                  model: 
                    type: string
                  stop_reason:
                    type: string
                    enum: [end_turn, stop_sequence]
                  stop_sequence:
                    type: string
                  usage:
                    type: object
                    properties:
                      input_tokens: 
                        type: integer
                      output_tokens:
                        type: integer
        '4XX':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    enum: [APIError, AuthenticationError, InvalidRequestError, NotFoundError, OverloadedError, PermissionError, RateLimitError]
                  error:
                    type: string